### ISSUE TITLE
doesn't work due to incorrect initialization

### ISSUE THREAD

**Issue by gsimko** [tomexsans/videojs-quality-selector-hls#4]
This plugin doesn't work at all due to a change compared to the original version. The event listener is only bound after the ready event is observed, but by then the quality level events have been already sent, so this plugin misses them all.

**Comment by gsimko** [comment]
The solution looks simple, just call this.onAddQualityLevel(); right before bindPlayerEvents.

**Comment by tomexsans** [comment]
hi @gsimko How can i simulate this error?

**Comment by gsimko** [comment]
@tomexsans I wish I knew why it doesn't happen on your system! It's deterministically happening on mine. Before we would delve deeper, can you try if videojs 8.5.2 still works for you? I see that video.js upgraded their videojs-contrib-quality-levels dependency in 8.4.2 , maybe that broke the setup?

**Comment by tomexsans** [comment]
Let me try using `VideoJs 8.5.2`

**Comment by tomexsans** [comment]
Hello @gsimko i was unable to simulate the error you have recieved using `Videojs 8.5.2`

`https://github.com/tomexsans/videojs-quality-selector-hls/tree/videojs-8.5.2`

Also using it on my VueJS3 Project i have not encountered any error. I'll close this issue with comments incase any issues arise.
